
-- dummy data for rms.Employee table
INSERT INTO EMPLOYEE (
    FIRST_NAME, LAST_NAME, GENDER, DOB, NATIONALITY,
    MARITAL_STATUS, PHONE, SUB_DIVISION, STATUS, HIRE_DATE,
    GRADE, DIVISION, EMAIL, OFFICE, ACTIVE )
VALUES (
    'Kholishul', 'Aziz', 'M', DATE '1991-04-01', 'IND',
    'M', '085730323302', 'Java Bootcamp', 'P', DATE '2013-11-18',
    'SE2', 'JWT', 'Kholishul.aziz@mitrais.com', 'JOG',
    TRUE);

INSERT INTO EMPLOYEE (
    FIRST_NAME, LAST_NAME, GENDER, DOB, NATIONALITY,
    MARITAL_STATUS, PHONE, SUB_DIVISION, STATUS, HIRE_DATE,
    GRADE, DIVISION, EMAIL, OFFICE, ACTIVE )
VALUES (
    'Abizar Athaillah', 'Aziz', 'M', DATE '2017-01-21', 'IND',
    'S', '081234567890', 'React Bootcamp', 'C', DATE '2017-01-21',
    'SE1', 'JWT', 'abizarathaillah.aziz@mitrais.com', 'DPS',
    FALSE);



-- dummy data for rms.History table
INSERT INTO HISTORY (
    START_DATE, END_DATE, NAME, ROLE, DESCRIPTION, EMPLOYEE_ID )
VALUES (
    '2014-01-01', '2016-09-01', 'MMS', 'DEV', 'MMS Description',
    (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Kholishul'));
INSERT INTO HISTORY (
    START_DATE, END_DATE, NAME, ROLE, DESCRIPTION, EMPLOYEE_ID )
VALUES (
    '2016-09-01', '2016-12-01', 'BTPN', 'DEV', 'BTPN Description',
    (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Kholishul'));
INSERT INTO HISTORY (
    START_DATE, END_DATE, NAME, ROLE, DESCRIPTION, EMPLOYEE_ID )
VALUES (
    '2014-01-01', null , 'CDC', 'DEV', 'CDC Description',
    (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Abizar Athaillah'));
INSERT INTO HISTORY (
    START_DATE, END_DATE, NAME, ROLE, DESCRIPTION, EMPLOYEE_ID )
VALUES (
    '2016-12-01', null , 'CDC', 'DEV', 'CDC Description',
    (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Kholishul'));



-- dummy data for rms.Lookup table
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('GRADE', 'JP', 'Junior Programmer');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('GRADE', 'PG', 'Programmer');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('GRADE', 'AP', 'Analyst Programmer');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('GRADE', 'AN', 'Analyst');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('GENDER', 'M', 'Male');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('GENDER', 'F', 'Female');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('NATION', 'IND', 'Indonesia');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('MARITAL', 'S', 'Single');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('MARITAL', 'M', 'Married');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('EMPSTAT', 'C', 'Contract');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('EMPSTAT', 'P', 'Permanent');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('DIV', 'JWT', 'Java Web Technology');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('OFFICE', 'JOG', 'Yogyakarta');
INSERT INTO LOOKUP(DATA_TYPE, DATA_CODE, DATA_DESC) VALUES('OFFICE', 'DPS', 'Denpasar');